### ISSUE TITLE
Error loading on 28.0.45

### ISSUE THREAD

**Issue by Sunekaer** [NinjaPhenix/Torcherino#12]
![image](https://user-images.githubusercontent.com/18720460/62561998-98c6c980-b880-11e9-9e64-80ddb396d6ac.png)
https://paste.dimdev.org/otixexalab.md

**Comment by NinjaPhenix** [comment]
Fixed in mod version [9.0.3](https://www.curseforge.com/minecraft/mc-mods/torcherino/files/2756466), and commit 9a52119995068bdb7efc4f08cfd702203214660d. The mod now requires forge 28.0.45 and above also.
