### ISSUE TITLE
i cannot install?

### ISSUE THREAD

**Issue by Yevano** [NinjaPhenix/Torcherino#16]
ok i try and tried to get it tow wwork even reinstall minecraft didnt work! And Then I try To Make New Folder for it EVEN. Then finaly i get it to work but THE COPILER CRASHES!! WHAT TO DO???!!

**Comment by sci4me** [comment]
I second this motion.

**Comment by NinjaPhenix** [comment]
Firstly, what is a copiler?
Also can you provide which mod loader and version (forge or fabric) and mod version your using.

**Comment by Yevano** [comment]
okay first of All i am not sure what a copiler is But SCI4ME was tellong me that that is how the plugin works sooooo... ?

i think i just use tekit so idk what is wrong! were do I Get The Crash Log ?

**Comment by sci4me** [comment]
whoooooa dude hold up
i have never said any words in my life

**Comment by Lemmmy** [comment]
It sounds like your Java version is incompatible with your mainframe chipset, you might need to send it back to Oracle if it's still within warranty. Try installing the Java enterprise edition developer kit (may cost you an arm and leg, but worth it for playing Minecraft at USS enterprise speeds). My grandma used to work on Turing machines from the early 30s and she had similar problems compiling her punch cards.

Also without logs it's hard to tell, but you might need to download more dedicated ram. Java is a very big compiler that needs a lot of memory to run on your computer.

But android devices have smaller amounts of ram so they have a stripped down version of Java called Dalvik Compiler for ARM RAM chips.  You could reverse engineer and port it to your computer if you use Linus.

**Comment by NinjaPhenix** [comment]
So I'm actually unable to get technic launcher to work on my computer but there should be a logs folder in the minecraft directory which should container a file called `latest.log`.

Also if you provide the minecraft version for the pack I'll be happy to try and find the latest version of torcherino for it.

( also do you actually need help or is this just joking around? )

**Comment by sci4me** [comment]
this is a very serious matter sir

**Comment by Yevano** [comment]
ok this is the File that I Found but i dk is this rite bcuz it doesnt EVEN say Torcherino!


java.lang.module.FindException: Module java.se.ee not found

[14:43:45] [Client thread/INFO]: Setting user: Yevano
[14:43:45] [Client thread/INFO]: (Session ID is token:dfacc43356b54812936c84cb46be1b1f:5312a93994b5476983f7d0ea5f4060c0)
[14:43:48] [Client thread/INFO]: LWJGL Version: 4.2.0
[14:43:52] [Client thread/INFO]: Reloading ResourceManager: Default
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000007fee37cc475, pid=10208, tid=8952
#
# JRE version: Java(TM) SE Runtime Environment (8.0_25-b18) (build 1.8.0_25-b18)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.25-b02 mixed mode windozer-amd24 compressed oops)
# Problematic frame:
# C  [KirkPicard.dll+0x302475]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Arch Centix
#
# An error report file with more information is saved as:
# C:\Users\Yevano\AppData\Roaming\.minecraft\hs_err_pid10208.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Java HotSpot(TM) 64-Bit Server VM warning: Scotty cannot beam us up!

**Comment by Yevano** [comment]
OMG im so sry idek y It Formmated It That AWay

**Comment by sci4me** [comment]
Yeah, pretty sure we all need help here...
