### ISSUE TITLE
Configs for sizes or other options

### ISSUE THREAD

**Issue by jusitnboggs** [NinjaPhenix/Torcherino#6]
I always seem to need 2 blocks above and below a torch but the only never charges from 3. 

Can we get a config to change the size of the torch mostly from 5x3x5 to 5x5x5 and  7x7x7 and 9x9x9  I would honestly be happy with the Y range being the only thing we can change but it would be nice to have full options to make custom sizes

**Comment by NinjaPhenix** [comment]
Thanks for the suggestion, I've receiving similar suggestions in the past so I'm going to make the range fully configurable in the next update  (forge update will take longer as it is less featured than the fabric version)

**Comment by jusitnboggs** [comment]
Thank you so much. Is fabric easier to dev for? I tried with forge a time or two didn't get very far.

**Comment by NinjaPhenix** [comment]
I'm really not too sure, I found it easy to get into to start with as theres very little changes to vanilla code so in most cases you just see how vanilla does it and use that, also now the api is split into sub modules so it's sort of easier to find what you may need. However a good way to get into developing is just to look at other people's code, actually figure out how it works, and apply it to your scenario.

**Comment by NinjaPhenix** [comment]
Hey, I finally managed to get the update out, not only can you now configure the torcherino ranges, but you also have a fancy new GUI, redstone interaction as well as the ability to define custom torcherino types (you will have to create assets for them though). Updated file can be found [here](https://www.curseforge.com/minecraft/mc-mods/torcherino/files/2733076). This is for 1.13.2 however I'll shortly be porting it to forge 1.14.x, fabric update might take a tad bit longer however.

**Comment by jusitnboggs** [comment]
Dude this all sounds awesome you have done more than I could hope for lol Thanks :)
    On Saturday, June 29, 2019, 09:08:49 PM PDT, NinjaPhenix <notifications@github.com> wrote:  
 
 
Hey, I finally managed to get the update out, not only can you now configure the torcherino ranges, but you also have a fancy new GUI, redstone interaction as well as the ability to define custom torcherino types (you will have to create assets for them though). Updated file can be found here. This is for 1.13.2 however I'll shortly be porting it to forge 1.14.x, fabric update might take a tad bit longer however.

**Comment by NinjaPhenix** [comment]
Going to be closing this issue now, fabric version is being updated now and will contain all the features of the forge version.
